services:
  backend:
    build:
      context: ./campify_backend
      dockerfile: Dockerfile
    container_name: campifyBackend
    volumes:
      - ./campify_backend:/campify_backend
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py init_tags &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./campify_frontend
      dockerfile: Dockerfile
    container_name: campifyFrontend
    depends_on:
      - backend
    ports:
      - "80:3000"